# Generated by Django 4.2.16 on 2024-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('appliances', models.CharField(choices=[('BK', 'Baking'), ('MX', 'Mixing'), ('FY', 'Frying'), ('ST', 'Straining'), ('MA', 'Mashing'), ('WH', 'Whisking'), ('CH', 'Chopping'), ('BL', 'Blending')])),
                ('method', models.TextField()),
                ('tag_cooked', models.IntegerField(choices=[(0, 'Not Cooked'), (1, 'Cooked')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
