# Generated by Django 4.2.16 on 2024-09-29 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0002_alter_rating_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_selection',
        ),
        migrations.AddField(
            model_name='comment',
            name='suggested_comment',
            field=models.CharField(blank=True, choices=[('Love this recipe!', 'Love this recipe!'), ('Delicious and easy to make.', 'Delicious and easy to make.'), ("OK, but probably won't make again.", "OK, but probably won't make again."), ('Too difficult for me, but might be OK for others', 'Too difficult for me, but might be OK for others')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='own_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user')},
        ),
    ]
