# Generated by Django 4.2.16 on 2024-09-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_recipe_original_recipe_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on', 'average_rating']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='mashing',
            new_name='microwaving',
        ),
    ]
