# Generated by Django 4.2.16 on 2024-10-01 10:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_remove_comment_comment_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
