# Generated by Django 4.2.16 on 2024-10-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0004_recipe_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_approved',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_site',
            field=models.CharField(choices=[('Accessible Chef', 'Accessible Chef'), ('CookABILITY', 'CookABILITY'), ('Other', 'Other')]),
        ),
    ]
