# Generated by Django 4.2.16 on 2024-10-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_recipe_owner_recipe_recipe_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_recipe',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_site',
            field=models.CharField(blank=True, choices=[('Accessible Chef', 'Accessible Chef'), ('CookABILITY', 'CookABILITY'), ('Other', 'Other')]),
        ),
    ]
