# Generated by Django 4.2.16 on 2024-10-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_alter_recipe_created_on_alter_recipe_original_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='own_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_approved',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Approved')], default=0),
        ),
    ]
