# Generated by Django 4.2.16 on 2024-10-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_alter_comment_own_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='suggested_comment',
        ),
    ]
